version: '3.5'

services:

    dashdot:
        image: mauricenino/dashdot:latest
        container_name: dashdot    
        ports:
            - "8200:3001"
        environment:
            DASHDOT_SHOW_HOST: 'true'
            DASHDOT_ENABLE_CPU_TEMPS: 'true'           
            DASHDOT_ENABLE_STORAGE_SPLIT_VIEW: 'true'
            DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
        volumes:
            - /:/mnt/host:ro
        privileged: 'true'
        restart: unless-stopped

        

